language: c
os: linux
compiler:
  - clang
  - gcc
before_script:
  - echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe" | sudo tee -a /etc/apt/sources.list
  - echo "deb-src http://us.archive.ubuntu.com/ubuntu/ trusty universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential libtool autotools-dev automake libssl-dev liblmdb-dev
  - ./autogen.sh
script:
  - ./configure
  - make
  - ./test/tests