language: c
os: linux
addons:
  apt:
    packages: build-essential libtool autotools-dev automake check liblmdb-dev libssl-dev
compiler:
  - clang
  - gcc
install:
  - sudo apt-get install build-essential libtool autotools-dev automake check liblmdb-dev libssl-dev
before_script:
  - ./autogen.sh
script:
  - ./configure
  - make check